execute:
  freeze: false

project:
  type: website
  render:
    - /chapters/*.qmd
    - index.qmd
  post-render:
    - "cp -rnv static/. _site/"

website:
  title: "Mise en production"
  navbar:
    background: "#447099"
    search: true
    align: center
    collapse-below: lg
    left:
      - href: chapters/introduction.qmd
        text: Introduction
      - text: Les bases
        menu:
          - href: chapters/linux-101.qmd
            text: Linux 101
          - href: chapters/git.qmd
            text: Git
      - text: Bonnes pratiques de développement
        menu:
          - href: chapters/code-quality.qmd
            text: Qualité du code
          - href: chapters/projects-architecture.qmd
            text: Structure des projets
          - href: chapters/big-data.qmd
            text: Traitement des données volumineuses
          - href: chapters/portability.qmd
            text: Portabilité
      - text: Mise en production
        menu:
          - href: chapters/deployment.qmd
            text: Déploiement
          - href: chapters/mlops.qmd
            text: MLOps
      - href: chapters/application.qmd
        text: Application
      - href: chapters/evaluation.qmd
        text: Evaluation
      - icon: github
        menu:
          - text: Site web
            url:  https://github.com/ensae-reproductibilite/website
          - text: Slides
            url:  https://github.com/ensae-reproductibilite/slides
          - text: Application fil rouge
            url:  https://github.com/ensae-reproductibilite/application-correction


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

eval: false

filters:
  - terminal
  - line-highlight
  - include-code-files
